<template>
  <div class="crumbs">
    <div class="content">
      <a href="">首页</a>/
      <a href="">新致商城</a>/
      <a href="">金融云</a>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'crumbs'
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.crumbs{    width: 100%;
  height: 50px;
  line-height: 50px;
  background-color: #F1F1F1;}
</style>
